-- ANDRE WATCHES — Fase 2: a porta
--
-- Aplicar pelo SQL Editor do Supabase, DEPOIS do schema.sql. É idempotente.
--
-- ⚠️ ESTE ARQUIVO FECHA O ACERVO. Assim que rodar, o site público para de
-- mostrar peças até as telas da Fase 2 existirem. Isso é intencional: a
-- proteção entra antes das telas, nunca depois — o contrário deixaria uma
-- janela de tempo com acervo exposto.

begin;

-- ─────────────────────────────────────────────────────────────────────────────
-- Clientes
--
-- A identidade mora no Supabase Auth (auth.users). Aqui ficam só os dados de
-- negócio. O `id` é o mesmo dos dois lados, então RLS consegue amarrar a sessão
-- ao status sem consulta extra.
--
-- `on delete cascade`: apagar o usuário no Auth apaga o cliente. Não sobra
-- registro órfão apontando para identidade que não existe mais.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists clientes (
  id             uuid primary key references auth.users (id) on delete cascade,
  nome           text not null,
  email          text unique not null,
  telefone       text,

  status         status_cliente not null default 'pendente',

  -- Contexto que a pessoa escreveu ao pedir acesso. Ajuda o Andre a decidir.
  observacao     text,

  criado_em      timestamptz not null default now(),
  ultimo_acesso  timestamptz
);

create index if not exists clientes_status_idx on clientes (status);

-- ─────────────────────────────────────────────────────────────────────────────
-- Pedidos de acesso
--
-- Um pedido ainda NÃO é uma identidade. Criar `auth.users` antes da aprovação
-- permitiria que qualquer pessoa ocupasse o e-mail de um futuro cliente. O
-- painel da Fase 3 cria a conta somente ao aprovar; até lá, esta é a fila.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists solicitacoes_acesso (
  id             bigint generated by default as identity primary key,
  nome           text not null check (char_length(nome) between 2 and 120),
  email          text unique not null check (char_length(email) <= 254),
  telefone       text not null check (char_length(telefone) <= 30),
  observacao     text check (char_length(observacao) <= 500),
  criado_em      timestamptz not null default now(),
  resolvido_em   timestamptz
);

alter table solicitacoes_acesso enable row level security;

-- Sem policy pública de propósito. A Server Action grava com a chave secret;
-- o navegador não lê, insere, altera nem descobre quem pediu acesso.

-- ─────────────────────────────────────────────────────────────────────────────
-- Quem é cliente ativo
--
-- Função em vez de subconsulta repetida: a regra fica num lugar só, e mudar o
-- que significa "pode ver" não exige caçar políticas.
--
-- `security definer` para poder ler `clientes` de dentro da política sem cair
-- em recursão de RLS.
-- ─────────────────────────────────────────────────────────────────────────────

create schema if not exists private;

create or replace function private.e_cliente_ativo()
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1 from public.clientes
    where id = (select auth.uid()) and status = 'ativo'
  );
$$;

revoke all on function private.e_cliente_ativo() from public;
grant usage on schema private to authenticated;
grant execute on function private.e_cliente_ativo() to authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- O acervo fecha
--
-- Não basta estar autenticado: um cliente recusado ou desativado continua com
-- login válido e não pode ver nada.
-- ─────────────────────────────────────────────────────────────────────────────

drop policy if exists pecas_leitura_publica on pecas;
drop policy if exists fotos_leitura_publica on fotos;

drop policy if exists pecas_leitura_cliente_ativo on pecas;
create policy pecas_leitura_cliente_ativo
  on pecas for select
  to authenticated
  using ((select private.e_cliente_ativo()));

drop policy if exists fotos_leitura_cliente_ativo on fotos;
create policy fotos_leitura_cliente_ativo
  on fotos for select
  to authenticated
  using ((select private.e_cliente_ativo()));

-- ─────────────────────────────────────────────────────────────────────────────
-- RLS de clientes
--
-- O cliente lê só o próprio registro — precisa disso para o nome na saudação.
-- Não pode alterar nada: mudar o próprio `status` seria escalada de privilégio.
-- Toda escrita passa pela chave secret, no servidor.
-- ─────────────────────────────────────────────────────────────────────────────

alter table clientes enable row level security;

drop policy if exists clientes_le_o_proprio on clientes;
create policy clientes_le_o_proprio
  on clientes for select
  to authenticated
  using (id = (select auth.uid()));

-- A primeira versão da migração criou a função no schema público. Depois que
-- as policies apontam para `private`, ela não tem mais dependentes nem motivo
-- para continuar exposta.
drop function if exists public.e_cliente_ativo();

commit;
